#define UTS_VERSION "7 Fri 1 Jul 12:29:53 BST 2022"
#define LINUX_COMPILE_TIME "12:29:53"
#define LINUX_COMPILE_BY "steve"
#define LINUX_COMPILE_HOST "Thor"
#define LINUX_COMPILE_DOMAIN "localdomain"
#define LINUX_COMPILER "gcc version 6.5.0 (GCC) "
